services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB: "aya_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432